name: CI Workflow for React App

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image using the Dockerfile.dev
    - name: Build Docker image with Dockerfile.dev
      run: |
        docker build -f Dockerfile.dev -t test-image .

    # Step 4: Run tests in the generated Docker image
    - name: Run tests inside the Docker container
      run: |
        docker run -e CI=true test-image npm run test
